import {StyleSheet} from 'react-native';
import {isIPhoneX, scaleSize} from "../../utils/ScreenUtils";

export const style = StyleSheet.create({
    container:{
        flex:1,
    },
    leftScrollView:{
        width:60,
        justifyContent:'center'
    },
    indicator:{
        width:4,
        height:20,
        borderRadius:4,
        position:'absolute',
        left:6,
        top:15,
    },
    ListFooterComponent:{
        width:WIDTH,
        height:170,
        justifyContent:'center',
        marginLeft:WIDTH/2/2
    },
    leftArrayView:{
        width:60,
        height:50,
        justifyContent:'center',
        alignItems:'center',
        flexDirection:'row'
    },
    leftLabelStyle:{
        fontSize:14,
    },
    renderSectionHeader:{
        width:WIDTH,
        height:35,
        justifyContent:'center',
    },
    renderSectionHeader1:{
        width:WIDTH-60,
        height:35,
        justifyContent:'center',
        alignItems:'center',
    },
    renderSectionHeaderTitle:{
        fontSize:12,
    },
    renderItemTitle:{
        width:WIDTH/3 +20,
        height:80,
        borderRadius:5,
        flexDirection:'row',
        alignItems:'center',
        marginLeft:10,
        marginBottom:10
    },
    itemTitle:{
        marginBottom:5,
        fontSize:13,
    },
    ItemView:{
        marginLeft:10,
    },
    bookCount:{
        fontSize:10,
    },

    bookItemImg:{
        position:'absolute',
        flexDirection:'row',
        width:WIDTH/5-10,
        alignItems:'flex-end',
        right:0,
        bottom:0,
    },
    bookItemImgView:{
        position:'absolute',
        bottom:0,
        width:42,
        height:60,
        zIndex:99,
        left:9
    },
    bookItemImgView1:{
        width:32,
        height:50
    },
    bookItemImgView2:{
        width:28,
        height:46
    },

    bookLoadView:{
        width:WIDTH,
        height:scaleSize(280),
        flexDirection:'row',
        alignItems:'center'
    },
    leftBookView:{
        width:scaleSize(140),
        height:scaleSize(200),
        borderRadius:5,
        marginLeft:20,
        shadowOffset: {width: 0, height: 0},
        shadowOpacity: 1,
        shadowRadius: 5,
        elevation: 10,
    },
    rightBookView:{
        marginLeft:20,
        justifyContent:'flex-end',
        height:110,
        width:WIDTH-(82+20+20+20),
    },
    BookViewTitle:{
        fontSize: IOS? 17 : 18,
        fontWeight: IOS ? '700' : '500',
    },
    BookViewContext:{
        fontSize:scaleSize(21),
        lineHeight:20,
        marginBottom:10,
        marginTop:10
    },
    latelyFollower:{
        fontSize:scaleSize(21),
        lineHeight:20
    },
    retentionRatio:{
        fontSize:scaleSize(21),
        lineHeight:20
    },
    bookLoadBottomView:{
        width:WIDTH-60,
        height:POXEL,
        position:'absolute',
        bottom:0,
        right:30
    },
    rightBookViewTitle:{
        width:60,
        height:10,
        marginTop:10,
        borderRadius:10
    },
    loadingMore:{
        width:WIDTH,
        height:40,
        justifyContent:'center',
        alignItems:'center',
        flexDirection:'row'
    },

    bookDetailViewTop:{
        width:WIDTH,
        height:HEIGHT/3,
        flexDirection:'row',
        alignItems:'center'
    },
    bookDetailViewTopLeftImg:{
        width:scaleSize(210),
        height:scaleSize(300),
        borderRadius:5,
        marginLeft:scaleSize(44),
    },
    bookDetailViewTopTextView:{
        width:WIDTH/2,
        height:scaleSize(300),
        marginLeft:scaleSize(44)
    },
    bookDetailViewTopRight:{
        width:WIDTH/2,
        height:10,
        borderRadius:10,
        marginTop:5
    },
    scoreLeft:{
        width:60,
        height:10,
        borderRadius:10,
        marginRight:10
    },
    score:{
        width:scaleSize(40),
        height:scaleSize(40),
    },
    bookDetailViewBottomView:{
        width:WIDTH,
        height:80,
        //flexDirection:'row',
        alignItems:'center'
    },
    IntroductionView:{
        width:WIDTH,
    },
    IntroductionTitle:{
        fontSize: IOS? 20 : 20,
        fontWeight: IOS ? '700' : '500',
        marginLeft:30,
        marginTop:30,
        marginBottom:10
    },
    IntroductionViewItem:{
        width:WIDTH-60,
        height:10,
        borderRadius:10,
        marginLeft:30,
        marginTop:15
    },
    bookBottomView:{
        position:'absolute',
        bottom:0,
        left:0,
        width:WIDTH,
        flexDirection:'row',
        height:isIPhoneX?80:60,

    },
    ChaseView:{
        width:WIDTH/2,
        height:60,
        justifyContent:'center',
        alignItems:'center'
    },
    dotChaseView:{
        width:WIDTH/2-30,
        height:40,
        justifyContent:'center',
        alignItems:'center',
        borderRadius:40
    },
    dotChaseTitle:{
        fontSize:18,
        fontWeight:'500'
    },
    bookDetailViewBottomTitle:{
        height:30,
        justifyContent:'center',
        alignItems:'center',
        width:80,
    },
    bookDetailViewBottomTitleStyle:{
        fontSize:14,

    },
    bookDetailViewTopTitleRight:{
        width:WIDTH/2,
        fontSize: 20,
        fontWeight: IOS ? '700' : '500',
    },
    scoreLeftTitle:{
        fontSize:20,
        fontWeight: IOS ? '700' : '500',
        color:'orange',
        marginRight:10
    },
    authorView:{
        fontSize:16,
    },
    wordCount1:{
        fontSize:12,
    },
    recommendedView:{
        width:WIDTH,
        alignItems:'center',
        justifyContent:'center',
        marginTop:20
    },
    recommended:{
        width:WIDTH-40,
        alignItems:'center',
        borderRadius:5,
    },
    recommendedTitle:{
        fontSize:20,
        fontWeight:'400',
        marginTop:20
    },
    recommendedContext:{
        fontSize:15,
        lineHeight:25,
        width:WIDTH-80,
        marginTop:10,
        marginBottom:20
    },
    IntroductionView1:{
        width:WIDTH,
        justifyContent:'center',
    },
    longIntroView:{
        width:WIDTH-60,
        justifyContent:'center',
        alignItems:'center',
        marginBottom:15,
        marginLeft:30
    },
    longIntro:{
        fontSize:16,
        width:WIDTH-60,
        lineHeight:30,
        marginTop:15
    },
    evaluationView:{
        width:WIDTH,
    },
    evaluationItemView:{
        width:WIDTH,
    },
    evaluationItemTopView:{
        flexDirection:'row',
        width:WIDTH,
        alignItems:'center',
        justifyContent:'space-between',
        paddingTop:20
    },
    evaluationItemImageView:{
        width:scaleSize(60),
        height:scaleSize(60),
        borderRadius:scaleSize(30),
        marginRight:15
    },
    avatarTitle:{
        fontSize:14,
        marginRight:10
    },
    avatarLvView:{
        borderWidth:POXEL,
        width:32,
        height:12,
        justifyContent:'center',
        alignItems:'center',
        borderRadius:15,
        marginLeft:15
    },
    avatarLv:{
        fontSize:10,
    },
    avatarContentView:{
        justifyContent:'center',
        alignItems:'center',
        width:WIDTH,
        marginTop:20
    },
    avatarContent:{
        fontSize:14,
        lineHeight:20,
        width:WIDTH-60
    },

    praise:{
        width:scaleSize(23),
        height:scaleSize(23),
        marginRight:10
    },
    allEvaluation:{
        width:WIDTH,
        height:scaleSize(150),
        justifyContent:'center',
        alignItems:'center',
    },
    evaluationViewTitle:{
        fontSize: IOS? 20 : 20,
        fontWeight: IOS ? '700' : '500',
        marginLeft:30
    },
    lookMoreView:{
        position:'absolute',
        right:30,
    },
    recommend_book:{
        width:WIDTH/3-10,
        justifyContent:'center',
        alignItems:'center',
    },
    recommend_image:{
        width:scaleSize(180),
        height:scaleSize(240),
        borderRadius:5,
        marginBottom:8,
        marginTop:20
    },
    chapter_view:{
        marginTop:20,
        marginLeft:20,
        marginBottom:20
    },
    chapter_title:{
        fontSize:20,
    },
    chapter_item:{
        height:40,
        justifyContent:'center',
        marginLeft:20
    },
    chapter_item_title:{
        fontSize:12,
    },
});